git:
  depth: 1

services:
  - docker

branches:
  only:
    - develop

jobs:
  include:
    - stage: build-nacos
      script:
        - image_tag=dev-nacos:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/nacos
        - docker build -f *.dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag registry.cn-shanghai.aliyuncs.com/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-elastic-search
      script:
        - image_tag=dev-elastic-search:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/elastic-search
        - docker build -f *.dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-sentinel
      script:
        - image_tag=dev-sentinel:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/sentinel
        - docker build -f *.dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag registry.cn-shanghai.aliyuncs.com/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-mysql
      script:
        - image_tag=dev-mysql:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/mysql
        - docker build -f Dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-cluster-redis
      script:
        - image_tag=dev-cluster-redis:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/redis
        - docker build -f cluster.dockerfile --build-arg password=$REDIS_PASSWORD -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-nginx
      script:
        - image_tag=dev-nginx:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/nginx
        - docker build -f Dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-standalone-redis
      script:
        - image_tag=dev-standalone-redis:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/redis
        - docker build -f redis.dockerfile --build-arg password=$REDIS_PASSWORD -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-activemq
      script:
        - image_tag=dev-activemq:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/activemq
        - docker build -f *.dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag registry.cn-shanghai.aliyuncs.com/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-rabbitmq
      script:
        - image_tag=dev-rabbitmq:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/rabbitmq
        - docker build -f Dockerfile --build-arg PGP_KEYSERVER=hkp://keys.gnupg.net -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag registry.cn-shanghai.aliyuncs.com/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    - stage: build-rabbitmq-management
      script:
        - image_tag=dev-rabbitmq-management:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - echo $image_tag
        - cd $project_home/dev-envs/rabbitmq/management
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - docker build -f Dockerfile --build-arg PGP_KEYSERVER=hkp://keys.gnupg.net --build-arg RABBITMQ_TAG=$image_tag -t $image_tag .
        - sudo docker tag $image_tag registry.cn-shanghai.aliyuncs.com/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

notifications:
  email:
    recipients:
      - zzhang_xz@163.com
    on_success: always # default: change
    on_failure: always # default: always

env:
  travis_wait: 50
  project_home: $PWD
  image_tag: 000
